defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      cs_path: "./casestudies/"
      cs_img_path: "../assets/images/wf/"

sass:
  style: compressed
  sass_dir: _sass